# base configuration
- name: wait for {{ inventory_hostname }}
  wait_for_connection:
    delay: 30
    timeout: 300

# hostname configuration
- name: change hostname to {{ inventory_hostname }}
  hostname:
    name: '{{ inventory_hostname }}'
  register: hostname
  tags:
    - rename

# temp to add dns ip until TGW resolved
- name: adding dns resolution for artifactory repo
  lineinfile:
    dest: /etc/hosts
    line: "{{ artifactory_ip }}   {{ artifactory_trusted_url }}"
    state: present
    insertafter: EOF
  tags:
    - artifactory

# add epel repo from artifactory
- name: install internal epel artifactory repo
  yum_repository:
    name: artifactory
    description: Internal GSA Artifactory Repo for use with GRACE PaaS (RPMs)
    baseurl: '{{ artifactory_epel_url }}'
    mirrorlist: '{{ artifactory_url }}'
    gpgcheck: no
    sslverify: no
  tags:
    - artifactory

# add pip.conf to allow use of pypi artifactory
- name: create pip.conf for use with pypi artifactory repo
  copy:
    dest: /etc/pip.conf
    force: yes
    content: |
      [global]
      index-url = {{ artifactory_pip_url }}
      trusted-host = {{ artifactory_trusted_url }}
    owner: root
    group: root
    mode: 666
  tags:
    - artifactory

# install python-pip
- name: install agent dependencies python-pip (redhat)
  yum:
    name: '{{ item.name }}'
    state: installed
    validate_certs: no
    disable_plugin: "*"
    disablerepo: "*"
    enablerepo: "artifactory"
  with_items:
    - '{{ redhat_agent_dependencies }}'
  tags:
    - artifactory

# install python-pip
- name: install agent dependencies nvme-cli (redhat)
  yum:
    name: '{{ artifactory_url }}/redhat/nvme-cli.rpm'
    state: installed
    disable_plugin: "*"
    disablerepo: "*"
    validate_certs: no
  tags:
    - artifactory

# install boto3, pytz from pip
- name: install boto3, orionsdk & pytz for use with acm certificate rotation & solarwinds
  pip:
    name:
      - pytz
      - orionsdk
      - boto3
  tags:
    - artifactory

# acm certificate rotation checking
- name: copy certificates to certificate store
  aws_acm_autorenew:
     hostname: '{{ inventory_hostname }}'
     passphrase: '{{ inventory_hostname }}'
     cert_path: '{{ local_cert_path }}/{{ inventory_hostname }}.pem'
     trust_path: '{{ local_cert_path }}/{{ inventory_hostname }}-trust.pem'
     key_path: '{{ local_key_path }}/{{ inventory_hostname }}.pem'
  notify: update-ca-trust
  ignore_errors: yes
  tags:
    - acm

# drive configuration
- name: look for nvme devices
  command: nvme list
  register: nvme_exist
  changed_when: False
  check_mode: no
  tags:
    - nvme_config

- name: map-ebs-nvme automation
  block:
    - name: copy map-ebs-nvme
      copy:
        src: files/map-ebs-nvme.sh
        dest: "/usr/local/bin/map-ebs-nvme"
        owner: root
        group: root
        mode: 0755
      tags:
        - nvme_config

    - name: configure map-ebs-nvme rules
      copy:
        src: files/map-ebs-nvme.rules
        dest: "/etc/udev/rules.d/map-ebs-nvme.rules"
        owner: root
        group: root
        mode: 0644
      tags:
        - nvme_config

    - name: run map-ebs-nvme
      command: /usr/local/bin/map-ebs-nvme
      tags:
        - nvme_config

  when: not(nvme_exist.stdout | regex_search('No NVMe devices detected.'))
