# wait for connection
- name: wait for {{ inventory_hostname }}
  wait_for_connection:

# hostname configuration (change)
- name: change hostname to {{ inventory_hostname }}
  win_hostname:
    name: '{{ inventory_hostname }}'
  register: hostname
  tags:
    - rename

# hostname configuration (reboot)
- name: reboot
  win_reboot:
  when: hostname.reboot_required
  tags:
    - rename

# domain configuration (change)
- name: add {{ inventory_hostname }} to the domain
  win_domain_membership:
    dns_domain_name: '{{ ent_domain.domain }}'
    hostname: '{{ inventory_hostname }}'
    domain_admin_user: '{{ ent_domain.username }}'
    domain_admin_password: '{{ ent_domain.password }}'
    domain_ou_path: '{{ ent_domain.ou }}'
    state: domain
  register: domain_state
  until: domain_state is success
  retries: 15
  delay: 10
  tags:
    - domain

# domain configuration (reboot)
- win_reboot:
  when: domain_state.reboot_required
  tags:
    - domain

# acm certificate rotation checking
- name: copy certificates to certificate folder
  win_aws_acm_autorenewal:
    hostname: '{{ inventory_hostname }}'
    passphrase: '{{ inventory_hostname }}'
    basepath: '{{ windows_acm_basepath }}'
    region: '{{ aws_region }}'
  ignore_errors: yes
  tags:
    - acm

# initial gpo policy pull
- name: refresh the GPO to ensure we have policy
  win_command: gpupdate /force
  tags:
    - domain
